# Generated by Django 5.2.1 on 2025-07-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(default='latest', max_length=100)),
                ('image_id', models.CharField(max_length=255, unique=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(db_column='host_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.dockerhost')),
            ],
        ),
    ]
