# Generated by Django 5.2.1 on 2025-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerrecord',
            name='internal_ports',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='containerrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='containerrecord',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='containerrecord',
            name='port_bindings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='containerrecord',
            name='restarted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='containerrecord',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='containerrecord',
            name='container_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='containerrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='containerrecord',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='containerrecord',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='containerrecord',
            name='status',
            field=models.CharField(default='created', max_length=100),
        ),
    ]
