# Generated by Django 5.2.1 on 2025-06-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "driver",
                    models.CharField(
                        choices=[
                            ("bridge", "Bridge"),
                            ("overlay", "Overlay"),
                            ("host", "Host"),
                            ("macvlan", "Macvlan"),
                            ("none", "None"),
                        ],
                        default="bridge",
                        max_length=20,
                    ),
                ),
                ("scope", models.CharField(default="local", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("internal", models.BooleanField(default=False)),
                ("attachable", models.BooleanField(default=False)),
                ("ingress", models.BooleanField(default=False)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networks",
                        to="api.dockerhost",
                    ),
                ),
            ],
        ),
    ]
