# Generated by Django 5.2.1 on 2025-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerrecord',
            name='volumes',
            field=models.ManyToManyField(blank=True, related_name='containers', to='api.volume'),
        ),
    ]
