# Generated by Django 5.2.1 on 2025-06-30 13:33

import uuid
from django.db import migrations, models

def gen_uuids(apps, schema_editor):
    DockerHost = apps.get_model('api', 'dockerhost')
    for host in DockerHost.objects.all():
        host.temp_uuid = uuid.uuid4()
        host.save(update_fields=["temp_uuid"])

def copy_data_from_old_to_new(apps, schema_editor):
        DockerHost = apps.get_model('api', 'dockerhost')
        for obj in DockerHost.objects.all():
            obj.old_id = obj.id
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_containerrecord_volumes'),
    ]

    operations = [
        # Add temporary null uuid field
        migrations.AddField(
            model_name='dockerhost',
            name='temp_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),

        # generate uuids
        migrations.RunPython(gen_uuids),

        # make uuid field unique
        migrations.AlterField(
            model_name="dockerhost",
            name="temp_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),

        # save old int ids
        migrations.AddField(
            model_name='dockerhost',
            name='old_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.RunPython(copy_data_from_old_to_new, reverse_code=migrations.RunPython.noop),

        # drop id as PK
        migrations.RemoveField(
            model_name='dockerhost',
            name='id',
        ),

        # rename temp uuid field to id
        migrations.RenameField(
            model_name='dockerhost',
            old_name='temp_uuid',
            new_name='id',
        ),

        # make uuid id field primary key
        migrations.AlterField(
            model_name='dockerhost',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False),
        ),

    ]
